version: '3.5'
services:
  db:
    image: mariadb:10.3
    environment: 
      MYSQL_ROOT_PASSWORD: "Keita0180"
      # MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: root
      # MYSQL_PASSWORD: Keita0180
    ports: 
      - '3306:3306'
    # env_file: production.env
    volumes: 
      - mysql-data:/var/lib/mysql/mysql.sock

  unicorn:
    build:
      context: .
      dockerfile: "Pro.Dockerfile"
    environment:
      - RAILS_ENV=production        
    command: bundle exec unicorn -p 3000 -c /setting_app/unicorn.conf.rb -E production 
    tty: true 
    stdin_open: true
    depends_on:
      - db 
    ports:
      - "3000:3000"
    env_file: production.env
    volumes:
      - .:/setting_app:cached 
      - tmp-data:/setting_app/tmp/sockets
      - public-data:/setting_app/public　

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: always
    volumes:
      - tmp-data:/setting_app/tmp/sockets
      - public-data:/setting_app/public
    depends_on:
      - unicorn

volumes:
  public-data:
  tmp-data:
  mysql-data:
    driver: local